#!/usr/bin/env python3
# -*- mode: python; -*-
#
# Copyright 2015 Canonical, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import logging
import sys
import shlex
from subprocess import check_output, DEVNULL
from functools import partial
from openstackci.log import setup_logger
from openstackci.tester import Tester


def parse_options(argv):
    parser = argparse.ArgumentParser(
        description='Ubuntu OpenStack Installer CI',
        prog='openstack-ci')
    parser.add_argument('-c', '--config', type=str, dest='config_file',
                        help="Profile to apply during CI.")
    parser.add_argument('-t', '--test',  type=str, dest='test_name',
                        help="Test to run.")
    parser.add_argument('-a', '--all', action='store_true', default=False,
                        dest='all_test',
                        help="Run all quality/regression tests.")
    parser.add_argument('-d', '--tests-directory', type=str, dest='test_dir',
                        help="Top level Location of quality/regression tests")
    parser.add_argument('--with-install', action='store_true', default=False,
                        dest='with_install',
                        help='Perform a full install and deploy before '
                        'running tests')
    return parser.parse_args(argv)


if __name__ == "__main__":
    opts = parse_options(sys.argv[1:])
    setup_logger()

    log = logging.getLogger('openstackci')

    if not opts.config_file:
        log.error("A configuration file is required to perform tests.")

    log.info("Initializing tests.")
    tester = Tester()

    if opts.with_install:
        cmd = ("sudo -E openstack-install -c {}".format(
            opts.config_file))
        tester.run_install(partial(check_output,
                                   shlex.split(cmd),
                                   stdout=DEVNULL,
                                   stderr=DEVNULL))

    # Perform tests.
    if opts.test_name:
        tester.run_test(opts.test_name)

    if opts.all_test:
        tester.run_all_tests()

    log.info("Test run complete.")
