.TH "" "" "" "" ""
.SH NAME
.PP
openstack\-ci\-web \- Ubuntu OpenStack Installer CI WebUI
.SH SYNOPSIS
.PP
usage: openstack\-ci\-web [\-h] [\-c CONFIG_FILE] [\-p HTTP_PORT] [\-d]
.PP
Ubuntu OpenStack Installer CI Web
.PP
optional arguments:
.IP
.nf
\f[C]
\-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ show\ this\ help\ message\ and\ exit
\-c\ CONFIG_FILE,\ \-\-config\ CONFIG_FILE
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ webserver\ config
\-p\ HTTP_PORT,\ \-\-port\ HTTP_PORT
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Port\ to\ listen\ on.
\-d,\ \-\-debug\ \ \ \ \ \ \ \ \ \ \ Debug\ mode
\f[]
.fi
.SH DESCRIPTION
.PP
Ubuntu OpenStack Installer CI WebUI is the web frontend to viewing tests
results.
