.TH "" "" "" "" ""
.SH NAME
.PP
openstack\-ci \- Ubuntu OpenStack Installer deployment testing
.SH SYNOPSIS
.TP
.B usage: openstack\-ci [\-h] [\-c CONFIG_FILE] [\-t TEST_NAME] [\-a] [\-d TEST_DIR]
[\-\-with\-install]
.RS
.RE
.PP
Ubuntu OpenStack Installer CI
.PP
optional arguments:
.IP
.nf
\f[C]
\-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ show\ this\ help\ message\ and\ exit
\-c\ CONFIG_FILE,\ \-\-config\ CONFIG_FILE
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Profile\ to\ apply\ during\ CI.
\-t\ TEST_NAME,\ \-\-test\ TEST_NAME
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Test\ to\ run.
\-a,\ \-\-all\ \ \ \ \ \ \ \ \ \ \ \ \ Run\ all\ quality/regression\ tests.
\-d\ TEST_DIR,\ \-\-tests\-directory\ TEST_DIR
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Top\ level\ Location\ of\ quality/regression\ tests
\-\-with\-install\ \ \ \ \ \ \ \ Perform\ a\ full\ install\ and\ deploy\ before\ running\ tests
\f[]
.fi
.SH DESCRIPTION
.PP
Ubuntu OpenStack Installer deployment testing provides a simple way to
test Single, Multi, and Landscape OpenStack Autopilot deployments.
.SH ENVIRONMENT VARIABLES
.PP
\f[B]JUJU_BOOTSTRAP_TO\f[] define a specific MAAS host to be used for
the initial juju bootstrap.
.IP
.nf
\f[C]
$\ JUJU_BOOTSTRAP_TO=machine\-a.maas\ openstack\-ci\ \-c\ config\-multi.yaml\ \-a\ \-\-with\-install
\f[]
.fi
