# Basic webserver configuration

# HTTP Port
port: 8080

# Secure cookie pass
cookie_secret: s3cr3ts4uc3!

# Run in debug mode
debug: true

# Master server
master_server_host = http://localhost:9000

# A unique token that workers will use to talk back to the ci service.
master_server_auth: 2012ceb2-ba77-4f56-98cf-d50172302e54

# Auto sync results to master ci server, set to true if contacting a remote ci server
auto_sync: false